apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      hostNetwork: true
      containers:
      - name: weather
        image: imannost/weather:v67
        env:
          - name: API-KEY
            valueFrom:
              secretKeyRef:
                key: api
                name: api-key