apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: {{$IMAGE}}
        ports:
          - containerPort: 80
        envFrom:
          - secretRef:
              name: api-key