apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  labels:
    app: weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: imannost/weather:v67
        ports:
          - containerPort: 80
        env:
          - name: API-KEY
            valueFrom:
              secretRef:
                name: api-key