- hosts: localhost
  collections:
    - kubernetes.core
  tasks:
  - name: Create a pod
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Pod
        metadata:
          name: "weather"
          namespace: default
          labels:
            app: galaxy
        spec:
          containers:
          - name: imannost/weather
            image: imannost/weather