apiVersion: v1
kind: Service
metadata:
  name: weather-svc
labels:
    owner: annaostanina
spec:
  selector:
    project: weather
  ports:
    - name: api-listener
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32000
  type: NodePort