apiVersion: v1
kind: Service
metadata:
  name: weather-svc
  namespace: default
spec:
  selector:
    project: weather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort